const Sequelize = require('sequelize')
const dbConfig = require('../config/database')

const Loja = require('../models/Loja')
const Categorias = require('../models/Categorias')
const Produtos = require('../models/Produtos')
const Categorias_prod = require('../models/Categorias_prod')
const Caracteristicas = require('../models/Caracteristicas')
const Fotos_prod = require('../models/Fotos_prod')
const Descontos = require('../models/Descontos')
const Pedidos = require('../models/Pedidos')
const Users = require('../models/Users')
const Cestas = require('../models/Cestas')
const Addresses = require('../models/Addresses')

const connection = new Sequelize(dbConfig)

Loja.init(connection)
Categorias.init(connection)
Produtos.init(connection)
Categorias_prod.init(connection)
Caracteristicas.init(connection)
Fotos_prod.init(connection)
Descontos.init(connection)
Pedidos.init(connection)
Users.init(connection)
Cestas.init(connection)
Addresses.init(connection)

Loja.associate(connection.models)
Categorias.associate(connection.models) 
Produtos.associate(connection.models) 
Categorias_prod.associate(connection.models) 
Caracteristicas.associate(connection.models) 
Fotos_prod.associate(connection.models) 
Descontos.associate(connection.models) 
Pedidos.associate(connection.models) 
Users.associate(connection.models) 
Cestas.associate(connection.models) 
Addresses.associate(connection.models) 

module.exports = connection